### ISSUE TITLE
Logo uses the wrong font

### ISSUE THREAD

**Issue by ewels** [nf-core/coproid#12]
New logo is great, but it's been created without the correct font. You need _Maven Pro Bold_ installed before you generate it - see [Logo Requirements](https://github.com/nf-core/logos#requirements)

---

NB: Same as https://github.com/nf-core/hic/issues/12 and lots of other places. We should really make a docker container or something that has all of the requirements so that people don't fall in to this trap. (@MaxUlysse has been talking about it for a while now 😆)

**Comment by apeltzer** [comment]
I never see this myself 🙈

**Comment by drpatelh** [comment]
Damn! I missed that too even though I normally hunt for it 

We even reviewed the logo! :see_no_evil:

**Comment by ewels** [comment]
Me every time I see a nf-core logo with the wrong font: 😆 

![fellaini-meme](https://user-images.githubusercontent.com/465550/56967287-32375e80-6b61-11e9-9407-c42a1e85db4e.jpg)

**Comment by apeltzer** [comment]
Done with #13

**Comment by pditommaso** [comment]
😂
