### ISSUE TITLE
Problem in the file download during Test run

### ISSUE THREAD

**Issue by gabrielinnocenti** [nf-core/coproid#38]
Hi,

I am using nextflow version 20.10.0.5430 and I am trying to run the test run using command

`nextflow run nf-core/coproid -profile test,docker`

But I got the warnings reported below:

`WARN: Unable to stage foreign file: https://raw.githubusercontent.com/nf-core/test-datasets/coproid/kraken.tar.gz (try 1) -- Cause: No PSK available. Unable to resume. WARN: Unable to stage foreign file: https://raw.githubusercontent.com/nf-core/test-datasets/coproid/genomes/bsubtilis/genome.fa (try 1) -- Cause: No PSK available. Unable to resume. WARN: Unable to stage foreign file: https://raw.githubusercontent.com/nf-core/test-datasets/coproid/kraken.tar.gz (try 2) -- Cause: No PSK available. Unable to resume. WARN: Unable to stage foreign file: https://raw.githubusercontent.com/nf-core/test-datasets/coproid/genomes/ecoli/genome.fa (try 1) -- Cause: No PSK available. Unable to resume. WARN: Unable to stage foreign file: https://raw.githubusercontent.com/nf-core/test-datasets/coproid/kraken.tar.gz (try 3) -- Cause: No PSK available. Unable to resume. WARN: Unable to stage foreign file: https://raw.githubusercontent.com/nf-core/test-datasets/coproid/genomes/bsubtilis/genome.fa (try 2) -- Cause: No PSK available. Unable to resume. WARN: Unable to stage foreign file: https://raw.githubusercontent.com/nf-core/test-datasets/coproid/genomes/ecoli/genome.fa (try 2) -- Cause: No PSK available. Unable to resume. WARN: Unable to stage foreign file: https://raw.githubusercontent.com/nf-core/test-datasets/coproid/genomes/bsubtilis/genome.fa (try 3) -- Cause: No PSK available. Unable to resume. WARN: Unable to stage foreign file: https://github.com/nf-core/test-datasets/raw/coproid/reads/metagenome.1.fastq.gz (try 1) -- Cause: No PSK available. Unable to resume.`

This brings the program to abort due to the impossibility to download the files for the Test run.
I wanted to understand what went wrong. Is it just a problem of Nextflow version or something else is going on?

Thank you for your attention

**Comment by maxibor** [comment]
Hi @gabrielinnocenti ,
This seems to be an underlying issue of the Java version you have installed on your machine. https://stackoverflow.com/questions/52574050/javax-net-ssl-sslexception-no-psk-available-unable-to-resume

I have no issue staging the foreign test files on my machine.

**Comment by gabrielinnocenti** [comment]
Thank so much.
